In [2]:
import torch

In [3]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [7]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
points = torch.tensor([4., 1., 5., 3., 2., 1.])
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
(float(points[0]), float(points[1]))

(4.0, 1.0)

In [10]:
points = torch.tensor([[4, 1], [5, 3], [2, 1]])
points

tensor([[4, 1],
        [5, 3],
        [2, 1]])

In [11]:
points.shape

torch.Size([3, 2])

In [12]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
points = torch.tensor([[4, 1], [5, 3], [2, 1]])
points

tensor([[4, 1],
        [5, 3],
        [2, 1]])

In [14]:
points[0, 1]

tensor(1)

In [15]:
points[0]

tensor([4, 1])

In [16]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([.2126, .7152, .0722])
img_t

tensor([[[-0.5346, -0.7613,  0.7779, -1.4300, -0.9307],
         [-1.2261,  1.5960,  0.6441, -1.2763, -0.1124],
         [-0.6230, -0.6284, -0.8696, -2.3454, -1.2815],
         [-2.0183,  1.0363, -0.2085,  0.3285, -0.6981],
         [ 0.4841, -1.9304,  0.2526, -1.5363,  1.5732]],

        [[-0.2930,  1.2138,  0.4327,  0.1698,  0.1784],
         [ 0.4695,  1.5551, -1.2823, -0.6927, -0.0596],
         [-1.7574, -1.6159,  1.4351,  1.8992,  0.4771],
         [ 0.1582, -0.4635,  0.8181,  0.2119,  0.3516],
         [-0.5867,  0.1783, -0.5121, -0.1189,  0.0657]],

        [[ 0.5527,  1.4617, -0.2140, -1.6112,  2.0653],
         [-0.7964, -1.2322,  0.6630,  0.9990,  1.0171],
         [-0.7456,  0.3325, -0.0992, -0.6060,  0.6136],
         [ 0.6206,  0.4908,  0.9038,  0.4879, -0.3969],
         [ 0.9457, -0.2703,  0.2455, -0.4590, -1.3970]]])

In [17]:
batch_t = torch.randn(2, 3, 5, 5)

In [55]:
batch_t

tensor([[[[-0.3931,  0.1803, -0.0423,  0.3829,  0.4416],
          [-0.0640,  1.5556, -0.0960, -0.3524, -0.1562],
          [ 1.6656, -1.5949,  1.2019,  0.2228, -1.0473],
          [-2.5424, -1.6926, -1.2644, -0.5309, -0.7390],
          [-0.1124,  0.3057,  0.6728, -0.9761,  1.4017]],

         [[-1.2305, -0.8023,  1.3008,  0.0546,  1.1058],
          [-0.6091,  0.5191,  0.3622,  1.1423,  0.1580],
          [ 0.6545,  0.9755, -0.1896, -0.4290,  1.5417],
          [-0.4910,  0.3291, -0.3541,  0.7433,  0.7658],
          [ 1.5660, -0.4388, -1.8571,  2.3964,  0.5759]],

         [[ 1.3430, -0.7632, -0.8078, -1.1484,  0.4083],
          [ 0.4539, -0.2756,  1.4815,  1.2153,  0.4402],
          [-0.7809, -1.7636, -0.4980,  0.2553, -0.8003],
          [-1.4649,  0.9499,  0.5115,  1.8958, -1.8266],
          [ 0.2827, -0.1447, -0.3887,  0.8262, -0.3963]]],


        [[[-0.4921,  1.3545,  1.6018, -0.8820,  0.4370],
          [-0.2096,  0.6384,  0.2816, -0.6146, -1.3000],
          [-0.2500,  0.

In [59]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)

img_gray_naive.shape

torch.Size([5, 5])

In [60]:
batch_gray_naive.shape

torch.Size([2, 5, 5])

In [70]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [71]:
img_weights = img_t * unsqueezed_weights

In [72]:
batch_weights = (batch_t * unsqueezed_weights)

In [73]:
batch_weights

tensor([[[[-8.3572e-02,  3.8324e-02, -9.0030e-03,  8.1412e-02,  9.3888e-02],
          [-1.3603e-02,  3.3072e-01, -2.0415e-02, -7.4914e-02, -3.3210e-02],
          [ 3.5410e-01, -3.3907e-01,  2.5553e-01,  4.7373e-02, -2.2265e-01],
          [-5.4052e-01, -3.5984e-01, -2.6882e-01, -1.1286e-01, -1.5711e-01],
          [-2.3892e-02,  6.4998e-02,  1.4303e-01, -2.0752e-01,  2.9800e-01]],

         [[-8.8003e-01, -5.7381e-01,  9.3035e-01,  3.9066e-02,  7.9089e-01],
          [-4.3566e-01,  3.7127e-01,  2.5901e-01,  8.1699e-01,  1.1298e-01],
          [ 4.6811e-01,  6.9769e-01, -1.3561e-01, -3.0681e-01,  1.1026e+00],
          [-3.5116e-01,  2.3539e-01, -2.5326e-01,  5.3162e-01,  5.4771e-01],
          [ 1.1200e+00, -3.1386e-01, -1.3282e+00,  1.7139e+00,  4.1186e-01]],

         [[ 9.6964e-02, -5.5105e-02, -5.8321e-02, -8.2917e-02,  2.9476e-02],
          [ 3.2775e-02, -1.9900e-02,  1.0697e-01,  8.7745e-02,  3.1780e-02],
          [-5.6381e-02, -1.2733e-01, -3.5958e-02,  1.8432e-02, -5.7782e-

In [74]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [75]:
img_t

tensor([[[-0.5346, -0.7613,  0.7779, -1.4300, -0.9307],
         [-1.2261,  1.5960,  0.6441, -1.2763, -0.1124],
         [-0.6230, -0.6284, -0.8696, -2.3454, -1.2815],
         [-2.0183,  1.0363, -0.2085,  0.3285, -0.6981],
         [ 0.4841, -1.9304,  0.2526, -1.5363,  1.5732]],

        [[-0.2930,  1.2138,  0.4327,  0.1698,  0.1784],
         [ 0.4695,  1.5551, -1.2823, -0.6927, -0.0596],
         [-1.7574, -1.6159,  1.4351,  1.8992,  0.4771],
         [ 0.1582, -0.4635,  0.8181,  0.2119,  0.3516],
         [-0.5867,  0.1783, -0.5121, -0.1189,  0.0657]],

        [[ 0.5527,  1.4617, -0.2140, -1.6112,  2.0653],
         [-0.7964, -1.2322,  0.6630,  0.9990,  1.0171],
         [-0.7456,  0.3325, -0.0992, -0.6060,  0.6136],
         [ 0.6206,  0.4908,  0.9038,  0.4879, -0.3969],
         [ 0.9457, -0.2703,  0.2455, -0.4590, -1.3970]]])

In [76]:
img_gray_weighted = img_weights.sum(-3)
img_gray_weighted

tensor([[-0.2833,  0.8118,  0.4594, -0.2989,  0.0789],
        [ 0.0176,  1.3626, -0.7323, -0.6946,  0.0069],
        [-1.4432, -1.2653,  0.8344,  0.8159,  0.1131],
        [-0.2711, -0.0757,  0.6061,  0.2566,  0.0744],
        [-0.2484, -0.3024, -0.2948, -0.4448,  0.2806]])

In [79]:
batch_gray_weighted = batch_weights.sum(-3)
batch_gray_weighted

tensor([[[-0.8666, -0.5906,  0.8630,  0.0376,  0.9143],
         [-0.4165,  0.6821,  0.3456,  0.8298,  0.1115],
         [ 0.7658,  0.2313,  0.0840, -0.2410,  0.8222],
         [-0.9974, -0.0559, -0.4851,  0.5556,  0.2587],
         [ 1.1165, -0.2593, -1.2132,  1.5660,  0.6813]],

        [[-0.2263, -0.2181, -0.0118, -1.3083,  0.2971],
         [-2.2272,  0.1925, -0.5762, -1.2995, -0.1873],
         [ 0.2851,  1.2156,  0.5902, -0.4343,  0.6023],
         [ 0.5447, -0.2816,  1.2718, -0.8622,  0.7800],
         [-1.5963,  0.4700,  0.4827, -0.9756,  0.5240]]])

In [109]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [111]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
img_gray_weighted_fancy

tensor([[-0.2833,  0.8118,  0.4594, -0.2989,  0.0789],
        [ 0.0176,  1.3626, -0.7323, -0.6946,  0.0069],
        [-1.4432, -1.2653,  0.8344,  0.8159,  0.1131],
        [-0.2711, -0.0757,  0.6061,  0.2566,  0.0744],
        [-0.2484, -0.3024, -0.2948, -0.4448,  0.2806]])

In [112]:
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy

tensor([[[-0.8666, -0.5906,  0.8630,  0.0376,  0.9143],
         [-0.4165,  0.6821,  0.3456,  0.8298,  0.1115],
         [ 0.7658,  0.2313,  0.0840, -0.2410,  0.8222],
         [-0.9974, -0.0559, -0.4851,  0.5556,  0.2587],
         [ 1.1165, -0.2593, -1.2132,  1.5660,  0.6813]],

        [[-0.2263, -0.2181, -0.0118, -1.3083,  0.2971],
         [-2.2272,  0.1925, -0.5762, -1.2995, -0.1873],
         [ 0.2851,  1.2156,  0.5902, -0.4343,  0.6023],
         [ 0.5447, -0.2816,  1.2718, -0.8622,  0.7800],
         [-1.5963,  0.4700,  0.4827, -0.9756,  0.5240]]])

In [113]:
weights_named = torch.tensor([.2126, .7152, .0722], names=['channels'])
weights_named

<ipython-input-113-1cb66e664e02>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  weights_named = torch.tensor([.2126, .7152, .0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [119]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
img_named

tensor([[[-0.5346, -0.7613,  0.7779, -1.4300, -0.9307],
         [-1.2261,  1.5960,  0.6441, -1.2763, -0.1124],
         [-0.6230, -0.6284, -0.8696, -2.3454, -1.2815],
         [-2.0183,  1.0363, -0.2085,  0.3285, -0.6981],
         [ 0.4841, -1.9304,  0.2526, -1.5363,  1.5732]],

        [[-0.2930,  1.2138,  0.4327,  0.1698,  0.1784],
         [ 0.4695,  1.5551, -1.2823, -0.6927, -0.0596],
         [-1.7574, -1.6159,  1.4351,  1.8992,  0.4771],
         [ 0.1582, -0.4635,  0.8181,  0.2119,  0.3516],
         [-0.5867,  0.1783, -0.5121, -0.1189,  0.0657]],

        [[ 0.5527,  1.4617, -0.2140, -1.6112,  2.0653],
         [-0.7964, -1.2322,  0.6630,  0.9990,  1.0171],
         [-0.7456,  0.3325, -0.0992, -0.6060,  0.6136],
         [ 0.6206,  0.4908,  0.9038,  0.4879, -0.3969],
         [ 0.9457, -0.2703,  0.2455, -0.4590, -1.3970]]],
       names=('channels', 'rows', 'columns'))

In [120]:
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named

tensor([[[[-0.3931,  0.1803, -0.0423,  0.3829,  0.4416],
          [-0.0640,  1.5556, -0.0960, -0.3524, -0.1562],
          [ 1.6656, -1.5949,  1.2019,  0.2228, -1.0473],
          [-2.5424, -1.6926, -1.2644, -0.5309, -0.7390],
          [-0.1124,  0.3057,  0.6728, -0.9761,  1.4017]],

         [[-1.2305, -0.8023,  1.3008,  0.0546,  1.1058],
          [-0.6091,  0.5191,  0.3622,  1.1423,  0.1580],
          [ 0.6545,  0.9755, -0.1896, -0.4290,  1.5417],
          [-0.4910,  0.3291, -0.3541,  0.7433,  0.7658],
          [ 1.5660, -0.4388, -1.8571,  2.3964,  0.5759]],

         [[ 1.3430, -0.7632, -0.8078, -1.1484,  0.4083],
          [ 0.4539, -0.2756,  1.4815,  1.2153,  0.4402],
          [-0.7809, -1.7636, -0.4980,  0.2553, -0.8003],
          [-1.4649,  0.9499,  0.5115,  1.8958, -1.8266],
          [ 0.2827, -0.1447, -0.3887,  0.8262, -0.3963]]],


        [[[-0.4921,  1.3545,  1.6018, -0.8820,  0.4370],
          [-0.2096,  0.6384,  0.2816, -0.6146, -1.3000],
          [-0.2500,  0.

In [121]:
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [122]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [143]:
gray_named = (img_named * weights_aligned).sum('channels')

In [152]:
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [151]:
(img_named * weights_aligned).sum('channels')

tensor([[-0.2833,  0.8118,  0.4594, -0.2989,  0.0789],
        [ 0.0176,  1.3626, -0.7323, -0.6946,  0.0069],
        [-1.4432, -1.2653,  0.8344,  0.8159,  0.1131],
        [-0.2711, -0.0757,  0.6061,  0.2566,  0.0744],
        [-0.2484, -0.3024, -0.2948, -0.4448,  0.2806]],
       names=('rows', 'columns'))

In [167]:
gray_named = (img_named[..., :3] * weights_named)

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [168]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [187]:
torch.tensor([1602, 2 , 3], dtype=torch.uint8)

tensor([66,  2,  3], dtype=torch.uint8)

In [188]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [189]:
short_points.dtype

torch.int16

In [190]:
double_points.dtype

torch.float64

In [191]:
double_points = torch.zeros(10, 2).double()
short_points = torch.zeros(10, 2).short()
double_points.dtype

torch.float64

In [217]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.zeros(10, 2).to(torch.short)
short_points.dtype

torch.int16

In [220]:
torch.randn(10)

tensor([ 0.7669, -0.1415,  0.2132,  0.1839, -0.7365, -0.3050, -0.7808, -1.2072,
        -1.2469,  0.4169])

In [221]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [242]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 1, 0)

In [243]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))